### PR TITLE
Change tod api

### PR DESCRIPTION
**Pull request by alanvardy**

### CODE REVIEW

**Comment by alanvardy** [comment]
Current dependencies on/for this PR:
* main
  * **PR #300** <a href="https://app.graphite.dev/github/pr/alanvardy/tod/300" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/alanvardy/tod/300?utm_source=stack-comment).

**Comment by alanvardy** [comment]
@stacksjb My next tod release is a large breaking change to the Tod API. It uses commands that are inspired by GitHub CLI https://cli.github.com/ .

It means that I can separate the commands into sections, makes the commands more intuitive and easier to remember, allows future expansion and provides both flags and interactive functionality.

But it is totally going to break your workflow. Once this is released you will need to use `tod issue create -p inbox -c "task text here"` to create a task using your library.

How can I coordinate with you to makes this as small a breakage as possible? Perhaps I can time the release of this so that you could update your workflow at the same time.

**Comment by alanvardy** [comment]
> > 
> 
> Commenting here to keep flow going. let me know when updates are made for a single NLP input and I can absolutely test and ensure that they are kept in sync. Thanks for your help!

Quick add is in, and unlike the others, this one doesn't require quotes.

```bash
tod -q Remember the milk #groceries
tod --quickadd Go for a run today
```

If you clone the repo and have rust installed you can run either `cargo build --release` and find the executable in target or run the command with `cargo run -- -q Remember the milk`.

**Comment by stacksjb** [comment]
Thx - I will test this later today!

**Comment by alanvardy** [comment]
> Thx - I will test this later today!

Hey @stacksjb just checking in with you on whether you've had the chance to look, is there anything I can do to assist?

**Comment by alanvardy** [comment]
Hey @stacksjb it's been a couple of weeks so I am going to merge with apologies for any breakages, and move onto the next things.

Let me know if you have any issues on your end, and I'll make sure to be responsive to them

**Comment by stacksjb** [comment]
Thx for the comments - sorry for delay.

I tested today and it seems that projects are not being parsed - if I add a "#Project" they are still only added to the inbox. It does parse @ and // correctly though. Is that expected? I seem to remember being able to add directly to projects (assuming they already existed).

**Comment by alanvardy** [comment]
Oh I found the problem.

If you do this:

```
tod -q "this is a test #project" 
```

it will put it in that project, but if you dont't quote

```
tod -q this is a test #project
```

It will consider the octothorpe `#` to be a bash comment and ignore everything after it, you can see it in the highlighting of my fish terminal

image

**Comment by stacksjb** [comment]
I should have caught that! Great point. Thanks!

**Comment by stacksjb** [comment]
Tested and works great! I'll push an updated workflow shortly. Thanks!

**Pull request merged**
